import Head from "next/head";
import Image from "next/image";
import style from "../styles/Home.module.css";
export default function Home() {
  return (
    <div className={`${style.mainRef} h-screen`}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <nav>
          <div className="flex justify-between border-2 border-red-400">
            <button className="pb-[0.2rem] pt-2 px-2 m-2 rounded-lg bg-[#1dfefe]">
              <Image src="/previous.png" width={`40%`} height={`40%`} />
            </button>
            <button className="flex flex-row items-center py-2 px-5 m-2 rounded-lg bg-[#1dfefe]">
              <div className="text pr-2">Connect Wallet</div>
              <Image src="/wallet.png" width={`40%`} height={`40%`} />
            </button>
          </div>
        </nav>
      </div>
    </div>
  );
}
